version: '3.8'

services:
  app:
    build: .
    container_name: wifi-attacker-app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./captures:/app/captures
      - ./dictionaries:/app/dictionaries
      - ./app.log:/app/app.log
      - ./evil_twin.log:/app/evil_twin.log
      - ./scripts:/app/scripts
      - ./app:/app/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:6.0
    container_name: wifi-attacker-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
